---
title: "Challenge-11"
author: "Janelle Tan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Challenge 11

### Step 1

```{r, eval=TRUE,echo=TRUE}
library(httr)
library(jsonlite)
library(tidyverse)

historic_state_data_url <- "https://api.covidactnow.org/v2/states.timeseries.json?apiKey=0b5c284acc36440f8ebfd493e79b4de4"

raw_data <- GET(historic_state_data_url)

```
<br>

### Step 2: Extracting data & Converting data frames

```{r, eval=TRUE,echo=TRUE}
data <- fromJSON(rawToChar(raw_data$content))

```
<br>

### Step 3: Exploring the data

```{r, eval=TRUE,echo=TRUE}
glimpse(data)

```
<br>

### Step 4: Questions

```{r, eval=TRUE,echo=TRUE}
# i. What is the population in various states of U.S.A?
# ii. What fraction of the population was infected ?
# iii. What fraction of infected persons recovered ?
# iv. What fraction of the population is currently vaccinated ?
# v. What was the transmission-like in the various states ?
# vi. How did the disease progress since it started ?

# Questions (i) - (iv) do not need historical data, we could have used the current data available on the webpage for this

# But, (v) - (vi) needs us to plot the values of transmission and cases on a periodical basis, therefore requiring time-series values

```
<br>

### Step 5: Mapping variables to questions

```{r, eval=TRUE,echo=TRUE}
# i. data$state , data$population
# ii. data$actuals$cases , data$state
# iii. data$actuals$cases - data$actuals$deaths , data$state
# iv. data$actuals$vaccinationsCompleted , data$state
# v. 

# To extract time-series data from the data-frame data
#  - It is contained in the variable `actualsTimeseries`, which is a data-frame itself
#  - Explore the dataset, `actualsTimeseries`, to know the variables contained in it

time_series <- data %>%
 unnest(actualsTimeseries) # <- to unravel the contents of a dataframe within a dataframe, use unnest

# - Then identify variables to be used for our question, we will need the `cdcTransmissionLevelTimeseries`
 
# - It is a list, because it has the transmission levels for various countries on different dates 
 
# - Each element of the list corresponds to a state and has dimension, 1332*3
 
# - We have learnt that we need to use `[[index]]` to access elements of a list
 
# - Therefore, for brevity's sake let us pick maybe 5 states of our choice, "AK" (Alaska), "CA" (California), "NJ" (New Jersey), "TN" (Tennessee), "DC" (District of Columbia)
 
# - Since the date across all the five states are the same, we can use the code below

# Creating a new dataframe with needed data
# Save date
time_series_transmission <- tibble(Date=time_series$cdcTransmissionLevelTimeseries[[which(data$state=="CA")]]$date)

# Transmission levels in each state
time_series_transmission$Alaska <- time_series$cdcTransmissionLevelTimeseries[[which(data$state=="AK")]]$
cdcTransmissionLevel

time_series_transmission$California <- time_series$cdcTransmissionLevelTimeseries[[which(data$state=="CA")]]$cdcTransmissionLevel

time_series_transmission$New_Jersey <- time_series$cdcTransmissionLevelTimeseries[[which(data$state=="NJ")]]$cdcTransmissionLevel

time_series_transmission$Tennessee <- time_series$cdcTransmissionLevelTimeseries[[which(data$state=="TN")]]$cdcTransmissionLevel

time_series_transmission$District_of_Columbia <- time_series$cdcTransmissionLevelTimeseries[[which(data$state=="DC")]]$cdcTransmissionLevel

print(head(time_series_transmission))


# (vi) `time_series$cases`, `state`

# New data-frame with dates
time_series_cases <- list(Alaska = time_series %>% filter(state=="AK") %>% select(date,cases))

# Cases of each state
time_series_cases$California <- time_series %>% filter(state=="CA") %>% select(date,cases)
time_series_cases$New_Jersey <- time_series %>% filter(state=="NJ") %>% select(date,cases)
time_series_cases$Tennessee <- time_series %>% filter(state=="TN") %>% select(date,cases)
time_series_cases$District_of_Columbia <- time_series %>% filter(state=="DC") %>% select(date,cases)



```
<br>

### Step 6: Analysing Data

```{r, eval=TRUE,echo=TRUE}
#for (i)

ggplot(data, aes(x=state,y=population)) + geom_bar(stat="identity") +labs(x="States",y="Population") + theme_bw()

#for (ii)
ggplot(data, aes(x=state,y=(data$actuals$cases/population))) + geom_bar(stat="identity") + labs(x="States",y="Infected (%)")+theme_bw()

#for (v); time series
time_series_transmission[seq(1,1300,by=100),]%>%
 pivot_longer(cols=Alaska:District_of_Columbia,names_to="Countries",values_to="Transmission") %>%
ggplot(aes(x=Date,y=Transmission,colour=Countries,group=Countries)) +
geom_point(show.legend=TRUE) + labs(x="Date",y="Transmission Level")+theme_bw()

#for (vi)
data_to_plot <- tibble(Date_Alaska = time_series_cases$Alaska$date[seq(1,1300,by=100)],
 Cases_Alaska = time_series_cases$Alaska$cases[seq(1,1300,by=100)],
 Date_California = time_series_cases$California$date[seq(1,1300,by=100)],
 Cases_California = time_series_cases$California$cases[seq(1,1300,by=100)],
 Date_New_Jersey = time_series_cases$New_Jersey$date[seq(1,1300,by=100)],
 Cases_New_Jersey = time_series_cases$New_Jersey$cases[seq(1,1300,by=100)],
 Date_Tennessee = time_series_cases$Tennessee$date[seq(1,1300,by=100)],
 Cases_Tennessee = time_series_cases$Tennessee$cases[seq(1,1300,by=100)],
 Date_District_of_Columbia = time_series_cases$District_of_Columbia$date[seq(1,1300,by=100)],
 Cases_District_of_Columbia = time_series_cases$District_of_Columbia$cases[seq(1,1300,by=100)])

data_to_plot

library(cowplot)

fig1<- ggplot(data_to_plot, aes(x=Date_Alaska,y=Cases_Alaska)) +
geom_point() + labs(x="Date",y="Cases", title="Alaska") + theme_bw()

fig2<- ggplot(data_to_plot, aes(x=Date_California,y=Cases_California)) +
geom_point() + labs(x="Date",y="Cases", title="California") + theme_bw()

fig3<- ggplot(data_to_plot, aes(x=Date_New_Jersey,y=Cases_New_Jersey)) +
geom_point() + labs(x="Date",y="Cases", title="New Jersey") + theme_bw()

fig4<- ggplot(data_to_plot, aes(x=Date_Tennessee,y=Cases_Tennessee)) +
geom_point() + labs(x="Date",y="Cases", title="Tennessee") + theme_bw()

fig5<- ggplot(data_to_plot, aes(x=Date_District_of_Columbia,y=Cases_District_of_Columbia)) +
geom_point() + labs(x="Date",y="Cases", title="District of Columbia") + theme_bw()

plot_grid(fig1 + theme(legend.justification = c(0,1), axis.text.x = element_text(size = 3)),
 fig2 + theme(legend.justification = c(1,0), axis.text.x = element_text(size = 3)),
 fig3 + theme(legend.justification = c(0,1), axis.text.x = element_text(size = 3)),
 fig4 + theme(legend.justification = c(1,0), axis.text.x = element_text(size = 3)),
 fig5 + theme(legend.justification = c(0,1), axis.text.x = element_text(size = 3)),
 align = "v", axis = "lr", nrow=3,
 ncol = 2,labels = LETTERS[1:5],
 rel_heights = c(1,2))


```
<br>

### Step 

```{r, eval=TRUE,echo=TRUE}


```
<br>

